name: Serve Flask App on Push

on:
  push:
    branches:
      - main

jobs:
  serve:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Kill previous Flask app
      run: |
        pkill -f "python app.py" || echo "No previous Flask app running"

    - name: Start Flask app
      run: |
        nohup python app.py &

    - name: Keep job running
      run: |
        while true; do echo "Flask app is running..."; sleep 60; done
